import { queryDb } from "@/lib/db";
import { formatDate } from "@/lib/utils";
import { Archive, FileText, UploadCloud } from "lucide-react";

export const dynamic = "force-dynamic";

type AdminReportRow = {
  report_id: string;
  report_type: string;
  generated_at: string;
  r2_report_path: string;
  course_code: string;
  course_name: string;
  semester_name: string;
  year_name: string;
  generated_by_name: string | null;
};

type SemesterArchiveRow = {
  archive_id: string;
  archive_label: string;
  archive_path: string;
  archived_at: string;
  notes: string | null;
  semester_name: string;
  year_name: string;
};

export default async function ArchivesPage() {
  const [reports, archives] = await Promise.all([
    queryDb<AdminReportRow>(`
      SELECT
        gr.report_id,
        gr.report_type,
        gr.generated_at,
        gr.r2_report_path,
        cm.course_code,
        cm.course_name,
        sm.semester_name,
        ay.year_name,
        f.faculty_name AS generated_by_name
      FROM public.generated_report gr
      JOIN public.course_offering co ON gr.offering_id = co.offering_id
      JOIN public.course_master cm ON co.course_id = cm.course_id
      JOIN public.semester_master sm ON co.semester_id = sm.semester_id
      JOIN public.academic_year ay ON sm.year_id = ay.year_id
      LEFT JOIN public.faculty f ON gr.generated_by = f.faculty_id
      ORDER BY gr.generated_at DESC
      LIMIT 50
    `),
    queryDb<SemesterArchiveRow>(`
      SELECT
        sa.archive_id,
        sa.archive_label,
        sa.archive_path,
        sa.archived_at,
        sa.notes,
        sm.semester_name,
        ay.year_name
      FROM public.semester_archive sa
      JOIN public.semester_master sm ON sa.semester_id = sm.semester_id
      JOIN public.academic_year ay ON sm.year_id = ay.year_id
      ORDER BY sa.archived_at DESC
      LIMIT 20
    `),
  ]);

  return (
    <div className="space-y-8">
      <section className="rounded-[28px] bg-[#2b4f8c] p-6 text-white shadow-[0_18px_50px_rgba(43,79,140,0.18)]">
        <p className="text-xs font-semibold uppercase tracking-[0.28em] text-white/60">
          Admin archive console
        </p>
        <h1 className="mt-2 text-3xl font-semibold">Reports, archives, and permanent records</h1>
        <p className="mt-2 max-w-2xl text-sm text-white/72">
          Generated files remain available for audit, accreditation, and semester end review.
        </p>
        <div className="mt-5 grid gap-3 sm:grid-cols-3">
          {[
            { label: "Generated reports", value: reports.length, icon: FileText },
            { label: "Semester archives", value: archives.length, icon: Archive },
            { label: "Storage target", value: "Cloudflare R2", icon: UploadCloud },
          ].map(({ label, value, icon: Icon }) => (
            <div key={label} className="rounded-2xl border border-white/10 bg-white/10 p-4 backdrop-blur">
              <Icon className="h-4 w-4 text-white/70" />
              <p className="mt-3 text-xs uppercase tracking-[0.18em] text-white/60">{label}</p>
              <p className="mt-1 text-lg font-semibold text-white">{value}</p>
            </div>
          ))}
        </div>
      </section>

      <section className="space-y-4">
        <h2 className="text-lg font-semibold text-[var(--color-ink)]">Recent Generated Reports</h2>
        <div className="panel-card overflow-hidden">
          <table className="w-full text-sm text-left">
            <thead className="bg-gray-50/70 text-gray-500 font-medium border-b border-black/5">
              <tr>
                <th className="px-5 py-3">Report</th>
                <th className="px-5 py-3">Course</th>
                <th className="px-5 py-3">Term</th>
                <th className="px-5 py-3">Generated By</th>
                <th className="px-5 py-3">Generated At</th>
                <th className="px-5 py-3 text-right">Download</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-black/5">
              {reports.length === 0 ? (
                <tr>
                  <td colSpan={6} className="px-5 py-10 text-center text-gray-500">
                    No generated reports yet.
                  </td>
                </tr>
              ) : (
                reports.map((report) => (
                  <tr key={report.report_id} className="hover:bg-gray-50/50 transition-colors">
                    <td className="px-5 py-3 font-medium text-[var(--color-ink)]">
                      {report.report_type.replace(/_/g, " ")}
                    </td>
                    <td className="px-5 py-3 text-gray-500">
                      {report.course_code} {report.course_name}
                    </td>
                    <td className="px-5 py-3 text-gray-500">
                      {report.semester_name} · {report.year_name}
                    </td>
                    <td className="px-5 py-3 text-gray-500">{report.generated_by_name ?? "System"}</td>
                    <td className="px-5 py-3 text-gray-500 text-xs">{formatDate(report.generated_at)}</td>
                    <td className="px-5 py-3 text-right">
                      <a
                        href={report.r2_report_path}
                        target="_blank"
                        rel="noreferrer"
                        className="text-[var(--color-accent)] hover:underline"
                      >
                        Open file
                      </a>
                    </td>
                  </tr>
                ))
              )}
            </tbody>
          </table>
        </div>
      </section>

      <section className="space-y-4">
        <h2 className="text-lg font-semibold text-[var(--color-ink)]">Archived Semesters</h2>
        <div className="panel-card overflow-hidden">
          <table className="w-full text-sm text-left">
            <thead className="bg-gray-50/70 text-gray-500 font-medium border-b border-black/5">
              <tr>
                <th className="px-5 py-3">Archive</th>
                <th className="px-5 py-3">Semester</th>
                <th className="px-5 py-3">Archived At</th>
                <th className="px-5 py-3">Notes</th>
                <th className="px-5 py-3 text-right">Path</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-black/5">
              {archives.length === 0 ? (
                <tr>
                  <td colSpan={5} className="px-5 py-10 text-center text-gray-500">
                    No semester archives have been recorded yet.
                  </td>
                </tr>
              ) : (
                archives.map((archive) => (
                  <tr key={archive.archive_id} className="hover:bg-gray-50/50 transition-colors">
                    <td className="px-5 py-3 font-medium text-[var(--color-ink)]">
                      {archive.archive_label}
                    </td>
                    <td className="px-5 py-3 text-gray-500">
                      {archive.semester_name} · {archive.year_name}
                    </td>
                    <td className="px-5 py-3 text-gray-500 text-xs">
                      {formatDate(archive.archived_at)}
                    </td>
                    <td className="px-5 py-3 text-gray-500">{archive.notes ?? "-"}</td>
                    <td className="px-5 py-3 text-right">
                      <a
                        href={archive.archive_path}
                        target="_blank"
                        rel="noreferrer"
                        className="text-[var(--color-accent)] hover:underline"
                      >
                        Open
                      </a>
                    </td>
                  </tr>
                ))
              )}
            </tbody>
          </table>
        </div>
      </section>
    </div>
  );
}
